version: 0.2

phases:
  install:
    commands:
      - echo "Starting build..."
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo initialize docker swarm
      - docker swarm init
  build:
    commands:
      - echo build stack
      - docker stack deploy --compose-file $CODEBUILD_SRC_DIR/docker-stack.yml vote
      - echo check services
      - docker stack services vote
